MonProjet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('monapp.urls')),
]

monapp/urls.py
from django.urls import path
from . import views
app_name='monapp'
urlpatterns = [
    path('', views.accueil, name='accueil'),
    path('a-propos/', views.a_propos, name='a_propos'),
    path('contact/', views.contact, name='contact'),
]

monapp/models.py
from django.db import models

# Create your models here.

monapp/views.py
from django.shortcuts import render

# Create your views here.

def accueil(request):
    return render(request, 'monapp/accueil.html')

def a_propos(request):
    return render(request, 'monapp/a_propos.html')

def contact(request):
    return render(request, 'monapp/contact.html')

monapp/templates/monapp/a_propos.html
{% extends 'monapp/base.html' %}
{% load static %}
{% block title %} À propos {% endblock %}
{% block content %}
    <h1>À propos</h1>
    <p>Cette application a été développé grâce à <strong>Django</strong> ci-dessous:</p>
<img src="{% static 'monapp/images/django.png' %}" width="300">
{% endblock %}

monapp/templates/monapp/accueil.html
{% extends 'monapp/base.html' %}
{% load static %}
{% block title %} Page d'accueil {% endblock %}

{% block content %}
<h1><strong>Bienvenu(e) sur notre site Django !</strong></h1>
    <h2> Vous êtes actuellement à la page d'accueil, veuillez utiliser la barre de navigation pour changer d'interface.</h2>
{% endblock %}

monapp/templates/monapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Mon app Django hehe{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'monapp/css/style.css' %}">
</head>
<body>
    <header>
    <nav>
        <ul>
            <li><a href="{% url 'monapp:accueil' %}">Page d'accueil</a></li>
            <li><a href="{% url 'monapp:a_propos' %}">À propos</a></li>
            <li><a href="{% url 'monapp:contact' %}">Contactez-nous</a></li>
        </ul>
    </nav>
</header>

<main>
    {% block content %}{% endblock %}
</main>

<footer>
    <p>© 2026 - MonProjet Django - Kossi Elie VIAGBO</p>
</footer>
</body>
</html>

monapp/templates/monapp/contact.html
{% extends 'monapp/base.html' %}
{% block title %} Section - Contact{% endblock %}
{% load static %}
{% block content %}
<h1>Contactez-nous</h1>

<form>
    <label>Nom :</label><br>
    <input type="text" autofocus required><br><br>

    <label>Prénom :</label><br>
    <input type="text" required><br><br>

    <label>Email :</label><br>
    <input type="email" required><br><br>

    <label>Message :</label><br>
    <textarea></textarea><br><br>

    <button type="submit">Envoyer</button>
</form>

<p>Email : django@gmail.com</p>
<p>Téléphone : +221 76 334 45 77</p>
{% endblock %}